package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTarg.java */

public class ASTarg extends SimpleNode {
  public ASTarg(int id) {
    super(id);
  }

  public ASTarg(LTLParser p, int id) {
    super(p, id);
  }

}
