package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTAttribute.java */

public class ASTAttribute extends SimpleNode {
  public ASTAttribute(int id) {
    super(id);
  }

  public ASTAttribute(LTLParser p, int id) {
    super(p, id);
  }

}
