package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTargList.java */

public class ASTargList extends SimpleNode {
  public ASTargList(int id) {
    super(id);
  }

  public ASTargList(LTLParser p, int id) {
    super(p, id);
  }

}
