package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTattributeDefinition.java */

public class ASTattributeDefinition extends SimpleNode {
  public ASTattributeDefinition(int id) {
    super(id);
  }

  public ASTattributeDefinition(LTLParser p, int id) {
    super(p, id);
  }

}
