package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTBiOp.java */

public class ASTBiOp extends SimpleNode {
  public ASTBiOp(int id) {
    super(id);
  }

  public ASTBiOp(LTLParser p, int id) {
    super(p, id);
  }

}
