package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTBinaryProposition.java */

public class ASTBinaryProposition extends SimpleNode {
  public ASTBinaryProposition(int id) {
    super(id);
  }

  public ASTBinaryProposition(LTLParser p, int id) {
    super(p, id);
  }

}
