package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTCompOp.java */

public class ASTCompOp extends SimpleNode {
  public ASTCompOp(int id) {
    super(id);
  }

  public ASTCompOp(LTLParser p, int id) {
    super(p, id);
  }

}
