package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTDummyVar.java */

public class ASTDummyVar extends SimpleNode {

  public ASTDummyVar(int id) {
    super(id);
  }

  public ASTDummyVar(LTLParser p, int id) {
    super(p, id);
  }

}
