package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTdateAttributeDef.java */

public class ASTdateAttributeDef extends SimpleNode {
  public ASTdateAttributeDef(int id) {
    super(id);
  }

  public ASTdateAttributeDef(LTLParser p, int id) {
    super(p, id);
  }

}
