package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTExpr.java */

import java.text.*;

public class ASTExpr extends SimpleNode {

    Attribute attr;

    public void setAttribute( Attribute attr ) {
	this.attr = attr;
    }

    public Attribute getAttribute() {
	return this.attr;
    }

public ASTExpr(int id) {
    super(id);
  }

  public ASTExpr(LTLParser p, int id) {
    super(p, id);
  }

}
