package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTformulaDefinition.java */

public class ASTformulaDefinition extends SimpleNode {
    
    String description;

    public void setDescription( String d ) {
	this.description = d;
    }

    public String getDescription() {
	return  this.description;
    }
  
  public ASTformulaDefinition(int id) {
    super(id);
  }

  public ASTformulaDefinition(LTLParser p, int id) {
    super(p, id);
  }

}
