package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTFormulaCall.java */

import java.util.*;

public class ASTFormulaCall extends SimpleNode {

    /** List of values for the paramers of this formula.*/
    ArrayList values;

    public void setValues( ArrayList values ) {
	this.values = values;
    }

    public ArrayList getValues() {
	return this.values;
    }
    
  public ASTFormulaCall(int id) {
    super(id);
  }

  public ASTFormulaCall(LTLParser p, int id) {
    super(p, id);
  }

}
