package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTFormula.java */

public class ASTFormula extends SimpleNode {

    String description;

    public void setDescription( String d ) {
	this.description = d;
    }

    public String getDescription() {
	return  this.description;
    }

  public ASTFormula(int id) {
    super(id);
  }

  public ASTFormula(LTLParser p, int id) {
    super(p, id);
  }

}
