package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTFinalFormula.java */

public class ASTFinalFormula extends SimpleNode {
    
    String description;

    public void setDescription( String d ) {
	this.description = d;
    }

    public String getDescription() {
	return  this.description;
    }
  public ASTFinalFormula(int id) {
    super(id);
  }

  public ASTFinalFormula(LTLParser p, int id) {
    super(p, id);
  }

}
