package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTLiteral.java */

import java.text.*;

public class ASTLiteral extends SimpleNode {

    SimpleDateFormat sdf;

    public void setDateParser( SimpleDateFormat sdf ) {
	this.sdf = sdf;
    }

    public SimpleDateFormat getDateParser() {
	return this.sdf;
    }

  public ASTLiteral(int id) {
    super(id);
  }

  public ASTLiteral(LTLParser p, int id) {
    super(p, id);
  }

}
