package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTNumOp.java */

public class ASTNumOp extends SimpleNode {
  public ASTNumOp(int id) {
    super(id);
  }

  public ASTNumOp(LTLParser p, int id) {
    super(p, id);
  }

}
