package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTnumberAttributeDef.java */

public class ASTnumberAttributeDef extends SimpleNode {
  public ASTnumberAttributeDef(int id) {
    super(id);
  }

  public ASTnumberAttributeDef(LTLParser p, int id) {
    super(p, id);
  }

}
