package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTProposition.java */

public class ASTProposition extends SimpleNode {
  public ASTProposition(int id) {
    super(id);
  }

  public ASTProposition(LTLParser p, int id) {
    super(p, id);
  }

}
