package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTrenaming.java */

public class ASTrenaming extends SimpleNode {
  public ASTrenaming(int id) {
    super(id);
  }

  public ASTrenaming(LTLParser p, int id) {
    super(p, id);
  }

}
