package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTstringAttributeDef.java */

public class ASTstringAttributeDef extends SimpleNode {
  public ASTstringAttributeDef(int id) {
    super(id);
  }

  public ASTstringAttributeDef(LTLParser p, int id) {
    super(p, id);
  }

}
