package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTStringList.java */

import java.util.*;

public class ASTStringList extends SimpleNode {

    /** Strings is a container of all the strings is the set. */
    TreeSet strings;

//    public ASTStringList() {
//	super();
//	strings = new ArrayList();
//   }

    public void setStrings(TreeSet strings) {
	this.strings = strings;
    }

    public TreeSet getStrings() {
	return this.strings;
    }

  public ASTStringList(int id) {
    super(id);
  }

  public ASTStringList(LTLParser p, int id) {
    super(p, id);
  }

}
