package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTsetAttributeDef.java */

public class ASTsetAttributeDef extends SimpleNode {
  public ASTsetAttributeDef(int id) {
    super(id);
  }

  public ASTsetAttributeDef(LTLParser p, int id) {
    super(p, id);
  }

}
