/* Generated By:JJTree: Do not edit this line. ASTTemplateFormula.java */

package org.processmining.analysis.ltlchecker.parser;

public class ASTTemplateFormula extends SimpleNode {

    String description;

    public void setDescription( String d ) {
	this.description = d;
    }

    public String getDescription() {
	return  this.description;
    }

  public ASTTemplateFormula(int id) {
    super(id);
  }

  public ASTTemplateFormula(LTLParser p, int id) {
    super(p, id);
  }

}
