/* Generated By:JJTree: Do not edit this line. ASTuse.java */

package org.processmining.analysis.ltlchecker.parser;

public class ASTuse extends SimpleNode {
  public ASTuse(int id) {
    super(id);
  }

  public ASTuse(LTLParser p, int id) {
    super(p, id);
  }

}
