package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTUnOp.java */

public class ASTUnOp extends SimpleNode {
  public ASTUnOp(int id) {
    super(id);
  }

  public ASTUnOp(LTLParser p, int id) {
    super(p, id);
  }

}
