package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTUnaryProposition.java */

public class ASTUnaryProposition extends SimpleNode {
  public ASTUnaryProposition(int id) {
    super(id);
  }

  public ASTUnaryProposition(LTLParser p, int id) {
    super(p, id);
  }

}
