package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTValueAttribute.java */

public class ASTValueAttribute extends SimpleNode {
  public ASTValueAttribute(int id) {
    super(id);
  }

  public ASTValueAttribute(LTLParser p, int id) {
    super(p, id);
  }

}
