package org.processmining.analysis.ltlchecker.parser;
/* Generated By:JJTree: Do not edit this line. ASTValues.java */

public class ASTValues extends SimpleNode {
  public ASTValues(int id) {
    super(id);
  }

  public ASTValues(LTLParser p, int id) {
    super(p, id);
  }

}
